# render.yaml

services:
  - name: melon-booking
    buildCommand: pip install -r requirements.txt
    startCommand: python3 seed_db.py && python3 server.py
    env:
      MY_ENV_VARIABLE: my_value
    routes:
      - path: /*
        type: web
        command: python3 server.py
